In [1]:
import numpy as np

In [2]:
## Tranformando uma lista do Python em um Array do NumPy
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

array = np.array(lista)

In [3]:
print(lista)
print(array)

print(type(lista))
print(type(array))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[1 2 3 4 5 6 7 8 9 0]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
## Array de Zeros
arrayZeros = np.zeros(10)

print(arrayZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
## Mundando o valor de um Array
array[0] = 9
print(array)

[9 2 3 4 5 6 7 8 9 0]


In [6]:
## Criando uma matriz de zeros
matrizZeros = np.zeros((5, 3))
print(matrizZeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(array.max()) ## Pegando o valor mais alto
print(array.min()) ## Pegando o valor mais baixo
print(array.std()) ## 
print(array.mean()) ## Pegando o valor a media dos valores
print(array.argmax()) ## Mostra aonde a valor mais alto esta
print(array.argmin()) ## ## Mostra aonde a valor mais baixo esta

9
0
2.9
5.3
0
9
