In [1]:
import numpy as np

In [2]:
## Tranformando uma lista do Python em um Array do NumPy
lista = [1, 2, 3, 4, 5, 6, 7]

array = np.array(lista)

In [3]:
print(lista)
print(array)

print(type(lista))
print(type(array))

[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
## Array de Zeros
arrayZeros = np.zeros(10)

print(arrayZeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
## Mundando o valor de um Array
array[0] = 9
print(array)

[9 2 3 4 5 6 7]


In [6]:
## Criando uma matriz de zeros
matrizZeros = np.zeros((5, 3))
print(matrizZeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(array.max()) ## Pegando o valor mais alto
print(array.min()) ## Pegando o valor mais baixo
print(array.std()) ## 
print(array.mean()) ## Pegando o valor a media dos valores
print(array.argmax()) ## Mostra aonde a valor mais alto esta
print(array.argmin()) ## ## Mostra aonde a valor mais baixo esta

9
2
2.231499907401901
5.142857142857143
0
1


In [8]:
## Criando um Array no NumPy
covidPositive = np.array(["Yes", "No", "Yes", "No", "Yes", "No", "Yes"])
print(covidPositive)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [9]:
## Retorna TRUE ou False se o dado estiver no Array
mask = (covidPositive == "Yes")
print(mask)

[ True False  True False  True False  True]


In [10]:
## Substituindo os YES/TRUE por C19
covidPositive[mask] = "C19"
print(covidPositive)

['C19' 'No' 'C19' 'No' 'C19' 'No' 'C19']
